### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by metaleap** [gorilla/template#2]
This project looks promising but what's the status? The readme outlines 3 "phases" in future form ("phase X _will_ achieve Y" etc). Is it "done"? Or is anyone actively using it? Has it been abandoned? On hold? TIA for satisfying my curiosity..  =)

**Comment by mickgardner** [comment]
Yep I'd love to know whether this project is "done" or "abandoned" too?

**Comment by benbarbour** [comment]
+1 I'm quite curious about this.

**Comment by moraes** [comment]
This project has stalled.

But there's some hope on the horizon.

Rob Pike is interested in having some kind of block mechanism in (text|html)/template: https://code.google.com/p/go/issues/detail?id=3812#c11

Particularly how it will look, we don't know. I think it would be clear enough if it used a semantics similar to zap's [1]:

```
    {{define "base"}}
      <html>
            <body>
              <header>
                    Welcome to the Zap World.
              </header>

              {{block "content"}}
                    <p>This is just a placeholder.</p>
              {{end}}

              <footer>
                    Copyright 2012 The Zap Team.
              </footer>
            </body>
      </html>
    {{end}}

    {{define "tutorial" "base"}}
      {{block "content"}}
            <p>Welcome to the Zap tutorial.</p>
      {{end}}
    {{end}}
```

But this is just an idea. If you have a different proposal, please detail it in the issue above.

[1] https://code.google.com/p/sadbox/source/browse/zap/doc.go

**Comment by liamstask** [comment]
hi! after reading through issue 3812, I still wasn't clear what the status of this effort is :) it seemed like perhaps you had abandoned it there, or at least stalled indefinitely?

i don't yet have a strong proposal to contribute, but i'd love to have a solid templating option that supports inheritance and/or composition as has been hinted at here.
